apiVersion: v1
kind: Service
metadata:
  name: demo-pd-client
spec:
  ports:
  - name: client
    port: 2379
  selector:
    app: pd
---
apiVersion: v1
kind: Service
metadata:
  name: demo-pd
spec:
  clusterIP: None
  ports:
  - name: peer
    port: 2380
  selector:
    app: pd
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: demo-pd-cluster
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pd
  serviceName: demo-pd
  template:
    metadata:
      labels:
        app: pd
    spec:
      containers:
      - name: pd
        image: localhost:5000/pingcap/pd
        command: ["/entrypoint.sh"]
        args:
        - --data-dir=/var/lib/pd
        - --name=$(MY_POD_NAME)
        - --peer-urls=http://0.0.0.0:2380
        - --advertise-peer-urls=http://$(MY_POD_NAME).$(MY_CLUSTER_NAME)-pd.$(MY_NAMESPACE).svc:2380
        - --client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://$(MY_POD_NAME).$(MY_CLUSTER_NAME)-pd.$(MY_NAMESPACE).svc:2379
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_CLUSTER_NAME
          value: demo
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: data
          mountPath: /var/lib
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: data
        emptyDir: {}
      - name: localtime
        hostPath:
          path: /etc/localtime
