apiVersion: v1
kind: Service
metadata:
  name: demo-tikv
spec:
  clusterIP: None
  ports:
  - name: peer
    port: 20160
  selector:
    app: tikv
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: demo-tikv-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tikv
  serviceName: demo-tikv
  template:
    metadata:
      labels:
        app: tikv
    spec:
      containers:
      - name: tikv
        image: localhost:5000/pingcap/tikv
        command: ["/tikv-server"]
        args:
        - --pd=$(MY_CLUSTER_NAME)-pd-client.$(MY_NAMESPACE).svc:2379
        - --data-dir=/var/lib/tikv
        - --addr=0.0.0.0:20160
        - --advertise-addr=$(MY_POD_NAME).$(MY_CLUSTER_NAME)-tikv.$(MY_NAMESPACE).svc:20160
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_CLUSTER_NAME
          value: demo
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: data
          mountPath: /var/lib
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: data
        emptyDir: {}
      - name: localtime
        hostPath:
          path: /etc/localtime
